Guias usadas:
- Creación, conexión con cliente Supabase y extracción de data https://supabase.com/docs/reference/python/initializing

Librerias

In [19]:
import sys
sys.executable

'c:\\Users\\Angelica\\Documents\\Temporal-Carrera\\PerceivoAI\\REPOS_GITHUB\\.venv\\Scripts\\python.exe'

In [82]:
import os
from dotenv import load_dotenv
import pandas as pd
import requests
from requests.auth import HTTPBasicAuth
from tqdm import tqdm
from pathlib import Path
import numpy as np

## Extract

In [6]:
def obtener_datos(endpoint, login, authtoken):
    # Asegurar que la carpeta exista
    Path("data/raw").mkdir(parents=True, exist_ok=True)


    datos = []
    page = 1
    barra= tqdm(desc=f"Descargando '{endpoint}'", unit=" páginas")

    while (True):
        url = f"https://api.jumpseller.com/v1/{endpoint}.json?page={page}&limit=50"
        r = requests.get(url, auth=HTTPBasicAuth(login, authtoken))
        if r.status_code != 200:
            print(f"❌ Error al obtener {endpoint}:", r.status_code)
            break

        data = r.json()
        if not data:
            break

        datos.extend(data)
        barra.update(1) # avanza la barra en 1 unidad
        page += 1

    barra.close()


    print(f"✅ Data obtenida: {endpoint.title()}. Total páginas {page-1}\n")
    datos= pd.json_normalize(datos)
    return datos

# datos.to_parquet(f"data/raw/{endpoint}_raw.parquet", index=False) # se almacena la data raw
    # datos.to_csv(f"data/raw/{endpoint}_raw.csv", index=False)

Probar que si se carga un archivo a **supabase**
- Guia oficial(click en Connect y seleccionar el proyecto para obtener las credenciales): 
  - https://supabase.com/dashboard/project/mbzsgavapsezblkypfwi?showConnect=true
  - https://supabase.com/docs/guides/troubleshooting/using-sqlalchemy-with-supabase-FUqebT
  
- pip install python-dotenv sqlalchemy psycopg2

In [7]:
def to_serializable(obj):
    if isinstance(obj, np.ndarray):
        return [to_serializable(x) for x in obj.tolist()]
    elif isinstance(obj, dict):
        return {k: to_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [to_serializable(x) for x in obj]
    else:
        return obj  # valores simples

# Ejemplo aplicado al df
# df["col_limpia"] = df["col_original"].apply(
#     lambda fila: json.dumps(to_serializable(fila))
# )

In [8]:
# para evitar problema como: can't adapt type 'numpy.ndarray'
# serializamos los valores array a str
import json
def preprocessing_supabase(data_extracted):
    
    col_to_serializar=[]
    for col in data_extracted.columns:
        if data_extracted[col].apply(lambda x: isinstance(x, (np.ndarray, dict, list))).any(): 
            col_to_serializar.append(col)
    # ['product.categories', 'product.images', 'product.variants', 'product.fields]

    # print(col_to_serializar)
    if col_to_serializar: # si hay columnas 
        for col in col_to_serializar:
            # data_extracted[col]=data_extracted[col].apply(lambda fila: json.dumps(fila.tolist()) if isinstance(fila, np.ndarray) else json.dumps(fila))

            data_extracted[col] = data_extracted[col].apply( lambda fila: json.dumps(to_serializable(fila)) )
            
        print(f'Dataframe serializado. \nColumnas Serializadas: {col_to_serializar}\n')
    else:
        print('Nada que serializar')
    # return data_extracted

In [ ]:
products_df= pd.read_parquet("data/raw/products_raw.parquet")
customers_df= pd.read_parquet("data/raw/customers_raw.parquet")
orders_df= pd.read_parquet("data/raw/orders_raw.parquet")
# data/raw/{endpoint}_raw.parquet

## Supabase
Conexion con el proyecto en supabase

In [9]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

# Load environment variables from .env
load_dotenv()

def conect2supabase():
    # Fetch variables
    USER = os.getenv("user")
    PASSWORD = os.getenv("password")
    HOST = os.getenv("host")
    PORT = os.getenv("port")
    DBNAME = os.getenv("dbname")

    # Construct the SQLAlchemy connection string
    DATABASE_URL = f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}?sslmode=require"

    # Create the SQLAlchemy engine
    engine = create_engine(DATABASE_URL)
    print('✅ Supabase: Conexión Exitosa')
    return engine
    # # Test the connection
    # try:
    #     with engine.connect() as connection:
    #         print("Connection successful!")
    # except Exception as e:
    #     print(f"Failed to connect: {e}")

Insertamos archivo de prueba

In [11]:
# hago el cambio a csv
# products_csv= products_df.

# endpoint= 'products'
# esquema= 'raw'
def insert2supabase(engine,esquema, endpoint, df):
    try: 
        table_name= f'{endpoint}_raw'
        df.to_sql(
            table_name,
            con=engine,
            schema=esquema, # el esquema debe estar creado previamente
            if_exists='append', #append para no soreescribir
            index=False
        )
        print(f'💾 Creación exitosa de la tabla {table_name} en el esquema {esquema}.\n')
    except Exception as e:
        print(f"Error para crear la tabla {table_name}: {e}")

In [29]:
endpoint='customers'
id_name= f"{endpoint[:-1]}.id"
id_name

'customer.id'

In [7]:
import pandas as pd
from sqlalchemy import inspect

def insert2supabase(engine, esquema, endpoint, df):
    table_name = f"{endpoint}_raw"
    full_table_name = f"{esquema}.{table_name}"

    try:
        inspector = inspect(engine)

        # 1️⃣ Verificar si la tabla ya existe en el esquema
        table_exists = inspector.has_table(table_name, schema=esquema)

        if not table_exists:
            # Crear tabla desde cero
            df.to_sql(
                table_name,
                con=engine,
                schema=esquema,
                if_exists="replace",  # replace crea la tabla si no existe
                index=False
            )
            print(f"💾 Tabla {full_table_name} creada con {len(df)} filas.")
            return

        # 2️⃣ Si la tabla ya existe, traer IDs existentes
        id_name= f"{endpoint[:-1]}.id" # tengo que limpiar la ultima letra
    
        with engine.connect() as conn:
            query = f'SELECT "{id_name}" FROM {full_table_name}'
            existing_ids = pd.read_sql( query, conn )[id_name].tolist()

        # 3️⃣ Filtrar solo las filas nuevas
        df_new = df[~df[id_name].isin(existing_ids)]

        if not df_new.empty:
            df_new.to_sql(
                table_name,
                con=engine,
                schema=esquema,
                if_exists="append",
                index=False
            )
            print(f"💾 {len(df_new)} nuevas filas insertadas en {full_table_name}.")
        else:
            print(f"ℹ️ No hay nuevas filas para insertar en {full_table_name}.")

    except Exception as e:
        print(f"❌ Error insertando en {full_table_name}: {e}")

Ejecución

In [12]:
load_dotenv()

login =  os.getenv('JUMPSELLER_LOGIN')
authtoken =  os.getenv('JUMPSELLER_AUTHTOKEN')

endpoints=[ "products","customers","orders"]

dataframes={}
for endpoint in endpoints:
    dataframes[f'df_{endpoint}']= obtener_datos(endpoint, login, authtoken)

Descargando 'products': 24 páginas [00:37,  1.56s/ páginas]

✅ Data obtenida: Products. Total páginas 24

Descargando 'customers': 33 páginas [00:20,  1.58 páginas/s]

✅ Data obtenida: Customers. Total páginas 33

Descargando 'orders': 34 páginas [00:32,  1.04 páginas/s]

✅ Data obtenida: Orders. Total páginas 34

In [14]:
dataframes.keys()

dict_keys(['df_products', 'df_customers', 'df_orders'])

In [15]:
for key, df in dataframes.items():
    print(key)
    preprocessing_supabase(df)

df_products
Dataframe serializado.
Columnas Serializadas: ['product.categories', 'product.images', 'product.variants', 'product.fields']

df_customers
Dataframe serializado.
Columnas Serializadas: ['customer.shipping_addresses', 'customer.billing_addresses', 'customer.customer_categories', 'customer.customer_additional_fields']

df_orders
Dataframe serializado.
Columnas Serializadas: ['order.promotions', 'order.products', 'order.additional_fields', 'order.shipping_taxes']

In [16]:
engine_supabase= conect2supabase()

✅ Supabase: Conexión Exitosa

In [40]:
esquema= 'raw'

# endpoint= ['products','orders','customers']
for key, df in tqdm(dataframes.items(), desc= 'Insertando en Supabase'):
    for endpoint in endpoints:
        if key.endswith(endpoint):
            insert2supabase(engine_supabase,esquema, endpoint, df)

Insertando en Supabase:  33%|███▎      | 1/3 [02:15<04:31, 135.76s/it]

💾 Tabla raw.products_raw creada con 1198 filas.

Insertando en Supabase:  67%|██████▋   | 2/3 [02:18<00:57, 57.42s/it]

💾 Tabla raw.customers_raw creada con 1617 filas.

Insertando en Supabase: 100%|██████████| 3/3 [02:26<00:00, 48.81s/it]

💾 Tabla raw.orders_raw creada con 1679 filas.

In [ ]:
# insertando nuevamente
insert2supabase(engine_supabase,esquema, 'customers', dataframes['df_customers'])

ℹ️ No hay nuevas filas para insertar en raw.customers_raw.

## Transform

Siguiente paso: extraer los datos raw de Supabase

**Consideraciones** en Supabase <p>
- Crear vistas en public para que apunten a las tablas en el esquema 'raw'.(sql editor)
```
CREATE VIEW public.customers_raw as
SELECT * FROM raw.customers_raw;

CREATE VIEW public.products_raw as
SELECT * FROM raw.products_raw;

CREATE VIEW public.orders_raw as
SELECT * FROM raw.orders_raw;
```

- Generación de Columnas de products_raw sin categorias. Se copia el resultado en un string *products_column*.
```
SELECT string_agg('"' || column_name || '"', ' , ')
FROM information_schema.columns
WHERE table_schema = 'raw'
  AND table_name   = 'products_raw'
  AND column_name <> 'product.categories';
  ```
- Configurar número máximo de filas que retorna por proyecto o usar paginación para traer por lotes(2da opción usada).

### FUNCIONES

In [4]:
# extrae todos los endpoints, ya no es necesario realizar el for fuera de la funcion

# Traer la información por lotes
# consideración hasta 5000 mil registros
    
def extract_supabase_raw(endpoint): # cambiar despues a endpoints(lista)
    name_table= f"{endpoint}_raw"
    rango= [0,1000,2000,3000,4000]
    # evaluar o almacenar mientras exista rango en la tabla si lanza el error entonces parar

    parts_table=[]

    if endpoint=='products': # columnas obtenidas luego de query en SQL EDITOR
        products_column=' "product.id" , "product.name" , "product.page_title" , "product.description" , "product.meta_description" , "product.price" , "product.cost_per_item" , "product.compare_at_price" , "product.weight" , "product.stock" , "product.stock_unlimited" , "product.stock_threshold" , "product.stock_notification" , "product.sku" , "product.brand" , "product.barcode" , "product.featured" , "product.reviews_enabled" , "product.status" , "product.shipping_required" , "product.type" , "product.days_to_expire" , "product.created_at" , "product.updated_at" , "product.package_format" , "product.length" , "product.width" , "product.height" , "product.diameter" , "product.google_product_category" , "product.images" , "product.variants" , "product.fields" , "product.permalink" , "product.discount" , "product.currency" '
        select_query=products_column
    else:
        select_query="*"

    # Obtener data de Supabase por partes
    for ind, valor in enumerate(rango):
        table_chunk = ( 
        supabase.table(name_table)
        .select(select_query)
        .range(valor,valor+999) # 0,999 , lo mismo= rango[ind]
        .execute()
            )
        if len(table_chunk.data): # si existe la tabla en ese rango
            parts_table.append(table_chunk.data)
        else:
            break

    completed_table =[]

    # Juntar todas las listas en una sola lista
    for i in range(len(parts_table)):
        completed_table+= parts_table[i]
    
    print(f'✅ Extracción correcta realizada para {name_table}')
    print(f"Filas: {len(completed_table)}\n")

    return pd.DataFrame(completed_table)

In [ ]:
import re
import pandas as pd

def normalizar_texto_localidad(texto ):
    """
    Normaliza nombres de ciudades o municipalidades.
    
    - texto: string a normalizar
    - reemplazos: diccionario de equivalencias
    """

    
    reemplazos= {
    "santiago centro": "Santiago",
    "santiago de chile": "Santiago",
    "santiago  ": "Santiago",
    "ssntiago": "Santiago",
    "santiago": "Santiago",
    "SANTIAGO": "Santiago",
    "vina del mar": "Viña del Mar",
    "viña del mar ": "Viña del Mar",
    "valparaiso": "Valparaíso",
    "valparaiso ": "Valparaíso",
    "puerto montt": "Puerto Montt",
    "punta arenas": "Punta Arenas",
    "chillan": "Chillán",
    "chillan viejo": "Chillán Viejo",
    "temuco ": "Temuco",
    "temuco": "Temuco",
    "arica": "Arica",
    "antofagasta": "Antofagasta",
    "rancagua": "Rancagua",
    "curico": "Curicó",
    "san pedro de la paz": "San Pedro de la Paz",
    "los angeles": "Los Ángeles",
    "los andes": "Los Andes",
    "la serena": "La Serena",
    "valdivia": "Valdivia",
    "providencia ": "Providencia",
    "san miguel ": "San Miguel",
    "nunoa": "Ñuñoa",
    "penalolen": "Peñalolén",
    "penaflor": "Peñaflor",
    "talcahuano ": "Talcahuano",
    "concepcion": "Concepción"
    }

    if pd.isna(texto):
        return "Sin especificar"
    
    # --- 1. Limpieza básica
    t = texto.strip().lower()
    
    # --- 2. Diccionario de equivalencias conocidas
    if t in reemplazos:
        return reemplazos[t]
    
    # --- 3. Correcciones genéricas
    t = re.sub(r'\s+', ' ', t)   # quitar dobles espacios
    t = t.title()                # Capitalización estándar
    
    # --- 4. Casos inválidos genéricos
    if t in ["Asd", "Chile", "Guamuchil", "Sin Especificar"]:
        return "Sin especificar"
    
    return t

In [298]:
import pandas as pd
import json

def transform_customers(df_raw):
    """
    Recibe el df raw de customers y devuelve un df limpio (customers_clean).
    
    Pasos aplicados:
    1. Selección de columnas relevantes
    2. Parseo de direcciones (ciudad, municipalidad, pais)
    3. Renombrado con prefijo 'cliente_'
    4. Tratamiento de nulos y creación de flags
    5. Generación de columna categórica para accepts_marketing
    """
    
    # --- 1. Selección de columnas relevantes
    columnas_filtro = [
        'customer.id',
        'customer.fullname',
        'customer.status',
        'customer.accepts_marketing',
        'customer.shipping_addresses'
    ]
    df = df_raw[columnas_filtro].copy()

    # --- Renombrado
    df = df.rename(columns={
        'customer.id': 'id_cliente',
        'customer.fullname': 'cliente_nombre',
        'customer.status':'status',
        'customer.accepts_marketing': 'acepta_marketing',
        'customer.shipping_addresses': 'direccion_envio'
    })

    
    # --- 2. Parseo de direcciones
    def parse_direcciones(fila):
        try:
            fila_parseada = json.loads(fila)
            if not fila_parseada:  # si está vacío
                return pd.Series([None, None, 'Chile'])
            
            dicc = fila_parseada[0]  # primer elemento (diccionario)
            return pd.Series([
                dicc.get('city'),
                dicc.get('municipality'),
                'Chile'
            ])
        except Exception:
            return pd.Series([None, None, 'Chile'])
    
    df[['cliente_ciudad', 'cliente_municipalidad', 'cliente_pais']] = (
        df['direccion_envio'].apply(parse_direcciones)
    )

    df['cliente_ciudad'] = df['cliente_ciudad'].apply(lambda x: normalizar_texto_localidad(x))


    df.drop(columns=['direccion_envio'], inplace=True)
    
    # --- 3. Renombrado de columnas
    # df.columns = [col.replace('customer.', 'cliente_') for col in df.columns]
    
    # --- 4. Tratamiento de nulos
    # Flags de missing

    # return df.columns
    for col in ['cliente_ciudad', 'cliente_municipalidad', 'acepta_marketing']:
        df[f'{col}_missing'] = (df[col].isna() | (df[col]== 'Sin especificar') ).astype(int)
    
    # Columnas categóricas → reemplazo por "Sin especificar"
    cols_categoricas = ['status', 'cliente_ciudad', 'cliente_municipalidad', 'cliente_pais']
    df[cols_categoricas] = df[cols_categoricas].fillna('Sin especificar')

    df['acepta_marketing'] = df['acepta_marketing'].fillna(False)
    
    # --- 5. Versión categórica de accepts_marketing
    df['marketing_cat'] = df['acepta_marketing'].map({
        True: 'Si',
        False: 'No'
    })
    
    # Resultado final
    customers_clean = df.copy()
    return customers_clean

In [309]:
def transform_products(df):
    columnas_filtro= ['product.id',
    'product.name',
    'product.price',
    'product.stock',
    'product.stock_unlimited',
    'product.stock_threshold',
    'product.stock_notification',
    'product.brand',
    'product.reviews_enabled',
    'product.status',
    'product.created_at',
    'product.updated_at',
    'product.currency']

    # --- 1. Filtro de columnas
    df = df[columnas_filtro].copy()
    
    # --- Renombrado
    df = df.rename(columns={
        'product.id':'id_producto',
        'product.name':'descripcion',
        'product.price':'precio',
        'product.stock': 'stock',
        'product.stock_unlimited': 'stock_ilimitado',
        'product.stock_threshold': 'umbral_stock',
        'product.stock_notification': 'notificacion_stock',
        'product.brand': 'marca',
        'product.reviews_enabled': 'reseñas_habilitadas',
        'product.status': 'estado',
        'product.created_at': 'fecha_creacion',
        'product.updated_at': 'fecha_actualizacion',
        'product.currency': 'moneda'
    })

    # --- 3. Relleno de categóricas
    cols_categoricas = ['descripcion', 'marca', 'estado', 'moneda']
    df[cols_categoricas] = df[cols_categoricas].fillna('Sin especificar')

    # --- 3. Manejo de fechas
    for col in ['fecha_creacion', 'fecha_actualizacion']:
        df[col] = pd.to_datetime(df[col], errors='coerce').dt.date  # solo YYYY-MM-DD

    # --- 4. Manejo de precio
    df['precio']=df['precio'].fillna(0)

    # Resultado final
    df_clean = df.copy()
    return df_clean

In [285]:
import pandas as pd
from rapidfuzz import process

def normalizar_empresas_envio(df, col="empresa_envio"): #empresa_envio
    """
    Normaliza la columna de empresas de envío:
    - Convierte valores numéricos a 'Sin especificar'
    - Corrige errores comunes de tipeo con fuzzy matching
    - Devuelve una nueva columna 'empresa_envio_normalizada'
    """

    # ✅ Catálogo oficial de empresas de envío
    empresas_validas = [
        "Envío Express",
        "Blue Express",
        "BluExpress Express",
        "BluExpress Priority",
        "Estándar a domicilio",
        "Estándar a sucursal",
        "Prioritario",
        "Prioritario a domicilio",
        "Prioritario a sucursal",
        "Correo Ordinario",
        "Sin especificar"
    ]

    # ✅ Función de limpieza
    def limpiar_empresa(x):
        if pd.isna(x):
            return "Sin especificar"
        x = str(x).strip()

        # si el valor parece numérico → error → lo tratamos como desconocido
        if x.replace(".", "").isdigit():
            return "Sin especificar"

        return x

    # ✅ Función de normalización con fuzzy
    def normalizar_empresa(x):
        x = limpiar_empresa(x)

        mejor = process.extractOne(x, empresas_validas, score_cutoff=30)
        return mejor[0] if mejor else "Sin especificar"

    # ✅ Aplicar la transformación
    df["empresa_envio"] = df[col].apply(normalizar_empresa)

    return df

In [314]:
import pandas as pd
import json
import numpy as np

def transform_orders(df_raw):
    """
    Recibe el df raw de orders y devuelve orders_clean.
    Aplica: selección, renombrado, parseo, mapeo, tratamiento de nulos y tipos.
    """
    
    columnas_filtro = [
        'order.id',
        'order.created_at',
        'order.currency',
        'order.total',
        'order.fulfillment_status',
        'order.shipping_method_name',
        'order.customer.id',
        'order.shipping_address.region',
        'order.shipping_address.country',
        'order.shipping_address.municipality',
        'order.products',
        'order.status',
        'order.shipment_status'
    ]
    
    df = df_raw[columnas_filtro].copy()
    
    # --- Renombrado
    df = df.rename(columns={
        'order.id': 'id_orden',
        'order.created_at': 'fecha_creacion',
        'order.currency': 'moneda',
        'order.total': 'precio_total',
        'order.fulfillment_status': 'estado_cumplimiento',
        'order.shipping_method_name': 'empresa_envio',
        'order.customer.id': 'id_cliente',
        'order.shipping_address.region': 'region_envio',
        'order.shipping_address.country': 'pais_envio',
        'order.shipping_address.municipality': 'municipalidad_envio',
        'order.products': 'productos',
        'order.status': 'estado_orden',
        'order.shipment_status': 'estado_envio'
    })
    
    # --- Tipos y nulos
    df['id_orden'] = pd.to_numeric(df['id_orden'], errors='coerce')
    df = df.drop_duplicates(subset='id_orden')
    
    df['fecha_creacion'] = pd.to_datetime(df['fecha_creacion'], errors='coerce').dt.date
    # df['fecha_completacion'] = pd.to_datetime(df['fecha_completacion'], errors='coerce').dt.date
    
    df['moneda'] = df['moneda'].fillna('CLP')
    df['precio_total'] = pd.to_numeric(df['precio_total'], errors='coerce').fillna(0).astype(int)
    

    df['id_cliente'] = df['id_cliente'].fillna(0).astype(int) #generar una columna si id_cliente tiene valor diferente a 0 'Registrado' sino 'No registrado'
    df['estado_cliente']= np.where(df['id_cliente'] != 0, 'Registrado', 'No Registrado')
    df['pais_envio'] = df['pais_envio'].fillna('Chile')
    

    # --- Parsear productos (extraer ids)
    def extraer_ids(productos):
        try:
            items = json.loads(productos) if isinstance(productos, str) else productos
            if isinstance(items, list):
                return ";".join(str(p.get("id")) for p in items if p.get("id"))
        except Exception:
            return None
    df['productos_ids'] = df['productos'].apply(extraer_ids)
    df.drop(columns=['productos'], inplace=True)

    df['estado_cumplimiento'] = df['estado_cumplimiento'].map({
        'unfulfilled': 'No cumplido',
        'fulfilled': 'Cumplido' })
    
    df['estado_orden'] = df['estado_orden'].map({
        "Abandoned": "Abandonada",
        "Paid": "Pagada",
        "Canceled": "Cancelada",
        "Created": "Creada",
        "Pending Payment": "Pendiente de pago" })
    
    df['estado_envio'] = df['estado_envio'].map({
        "No Procesado": "No procesado",
        "Entregado": "Entregado",
        "Solicitado": "Solicitado",
        "No Aplicable": "No aplicable",
        "En Tránsito": "En tránsito"  })

    # nulos
    cols = ['estado_cumplimiento', 'region_envio', 'municipalidad_envio','estado_orden','estado_envio'] #empresas_envio
    df[cols] = df[cols].fillna('Sin especificar')

    # normaliza empresas de envio
    df = normalizar_empresas_envio(df)
    
    
    return df

In [288]:
import pandas as pd

def create_orders_products(df_orders, col_order="id_orden", col_products="productos_ids"):
    """
    Crea una tabla de relación orders_products a partir de un dataframe de órdenes.
    df_orders: DataFrame con al menos las columnas id_order y id_producto (string con ';' separados).
    col_order: nombre de la columna con el id de la orden.
    col_products: nombre de la columna con los ids de productos (str separados por ';').
    """
    
    # copiar para no alterar df original
    df_rel = df_orders[[col_order, col_products]].copy()
    
    # separar productos en listas
    df_rel[col_products] = df_rel[col_products].astype(str).str.split(";")
    
    # "explotar" listas en filas
    df_rel = df_rel.explode(col_products).reset_index(drop=True)
    
    # convertir id_producto a entero si es posible
    df_rel[col_products] = pd.to_numeric(df_rel[col_products], errors="coerce").astype("Int64")
    
    # renombrar columnas para consistencia
    df_rel = df_rel.rename(columns={
        col_order: "id_orden",
        col_products: "id_producto"
    })
    
    return df_rel

### FLUJO DE EJECUCIÓN - Extracción

1. **Extracción** de data_raw en supabase

In [1]:
import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()
url= os.environ.get("SUPABASE_URL")
key= os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

In [7]:
# endpoints
# customers_raw=extract_supabase_raw(endpoint='customers')
# products_raw= extract_supabase_raw('products')
# orders_raw= extract_supabase_raw('orders')
from tqdm import tqdm
endpoints=['products', 'customers', 'orders']

df_raw= {}
for endpoint in tqdm(endpoints):
    df_raw[f'{endpoint}_raw']= extract_supabase_raw(endpoint=endpoint) #funcion definida en Seccion de FUNCIONES

 33%|███▎      | 1/3 [00:06<00:12,  6.25s/it]

✅ Extracción correcta realizada para products_raw
Filas: 1230

 67%|██████▋   | 2/3 [00:07<00:03,  3.38s/it]

✅ Extracción correcta realizada para customers_raw
Filas: 1652

100%|██████████| 3/3 [00:10<00:00,  3.52s/it]

✅ Extracción correcta realizada para orders_raw
Filas: 1781

In [8]:
df_raw.keys()

dict_keys(['products_raw', 'customers_raw', 'orders_raw'])

2. Aplica funciones realizadas para cada tabla (customers, products, orders) y se generan data_clean
3. Se carga a supabase(configurar nuevo esquema)

In [299]:
# recuerda que las transformaciones se realizan sobre todo el dataset, entonces al cargarlas a supabase, hay que subirlas las que no esten en las tablas
# osea no repetir filas(verificar por id)
customer_clean=transform_customers(df_raw['customers_raw'])
customer_clean.head(5)

C:\Users\Angelica\AppData\Local\Temp\ipykernel_26940\2890642026.py:75: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['acepta_marketing'] = df['acepta_marketing'].fillna(False)

,id_cliente,cliente_nombre,status,acepta_marketing,cliente_ciudad,cliente_municipalidad,cliente_pais,cliente_ciudad_missing,cliente_municipalidad_missing,acepta_marketing_missing,marketing_cat
0,17276830,Francisca Fuenzalida,approved,False,La Serena,La Serena,Chile,0,0,0,No
1,15462049,Oscar Herrera,approved,False,Marga Marga,Quilpué,Chile,0,0,0,No
2,17506887,Julio Fuenzalida Cortes,approved,False,Santiago,Ñuñoa,Chile,0,0,0,No
3,16776276,a.avalos33@hotmail.com,approved,True,Sin especificar,Sin especificar,Chile,1,1,0,Si
4,16979494,Alexis Burgos Arcos,approved,False,Osorno,Osorno,Chile,0,0,0,No

In [22]:
len(customer_clean) == customer_clean['cliente_id'].nunique()

True

In [19]:
products_clean= transform_products(df_raw['products_raw'])
products_clean.head(2)

,producto_id,producto_name,producto_price,producto_stock,producto_stock_unlimited,producto_stock_threshold,producto_stock_notification,producto_brand,producto_reviews_enabled,producto_status,producto_created_at,producto_updated_at,producto_currency
0,27766653,Cámara Canon Mirrorless EOS R8 Body,1999990,1,False,0,True,Canon,True,available,2024-11-23,2025-08-12,CLP
1,27766654,Cámara Canon Mirrorless EOS R6 MKII Body,2989990,1,False,0,True,Canon,True,available,2024-11-23,2025-08-05,CLP

In [20]:
len(products_clean) == products_clean['producto_id'].nunique()

True

In [315]:
orders_clean= transform_orders(df_raw['orders_raw'])
orders_clean.head(2)

,id_orden,fecha_creacion,moneda,precio_total,estado_cumplimiento,empresa_envio,id_cliente,region_envio,pais_envio,municipalidad_envio,estado_orden,estado_envio,estado_cliente,productos_ids
0,2679,2025-08-27,CLP,167990,No cumplido,Envío Express,0,O'Higgins,Chile,Marchihue,Abandonada,No procesado,No Registrado,28363657
1,2678,2025-08-27,CLP,839990,No cumplido,Envío Express,17569269,Región Metropolitana,Chile,Vitacura,Pagada,No procesado,Registrado,27766673

In [312]:
len(orders_clean) == orders_clean['id_orden'].nunique()

True

In [304]:
orders_products = create_orders_products(orders_clean)
orders_products.head(5)

   id_orden  id_producto
0      2679     28363657
1      2678     27766673
2      2677     27831873
3      2676     29248187
4      2675     27795774

**Revisar**:
- chequeo generar que las data_clean esten correctas, valores adecuados, etc
- integrarlas todas las funciones en un archivo .py 'transform' 
- probar flujo correcto
- cargar los nuevos datasets a supabase (data_clean) cómo gestionas valores adicionales en supabase(usar misma lógica para verificar id existentes)

### PASOS REALIZADOS 
Pasos, consideraciones realizadas, previas para realizar las funciones

#### **Función TRANSFORM para customers_raw** <p>
Establecer los pasos, hacer pruebas y modularizar.
1. Filtrar columnas no a utilizar

In [51]:
df_raw['customers_raw'].head(2)

,customer.id,customer.email,customer.phone,customer.phone_prefix,customer.status,customer.accepts_marketing,customer.accepted_marketing_at,customer.cancelled_marketing_at,customer.fullname,customer.unconfirmed_email,customer.shipping_addresses,customer.billing_addresses,customer.customer_categories,customer.customer_additional_fields
0,17276830,123franhornig@gmail.com,936993176,+56,approved,False,None,None,Francisca Fuenzalida,None,"[{""name"": ""Francisca"", ""surname"": ""Fuenzalida""...","[{""name"": ""Francisca"", ""surname"": ""Fuenzalida""...",[],"[{""id"": 29701399, ""label"": ""accepts_marketing""..."
1,15462049,2tcloud@jumpseller-mercadolibreapp.com,None,None,approved,False,None,None,Oscar Herrera,None,"[{""name"": ""2TCLOUD"", ""surname"": ""-"", ""address""...","[{""name"": ""oscar"", ""surname"": ""herrera"", ""addr...",[],[]

In [20]:
df_raw['customers_raw'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1652 entries, 0 to 1651
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   customer.id                          1652 non-null   int64
 1   customer.email                       1652 non-null   object
 2   customer.phone                       1514 non-null   object
 3   customer.phone_prefix                1434 non-null   object
 4   customer.status                      1652 non-null   object
 5   customer.accepts_marketing           1651 non-null   object
 6   customer.accepted_marketing_at       1145 non-null   object
 7   customer.cancelled_marketing_at      0 non-null      object
 8   customer.fullname                    1652 non-null   object
 9   customer.unconfirmed_email           0 non-null      object
 10  customer.shipping_addresses          1652 non-null   object
 11  customer.billing_addresses           1652 non-null   object
 12  customer.customer_categories         1652 non-null   object
 13  customer.customer_additional_fields  1652 non-null   object
dtypes: int64(1), object(13)
memory usage: 180.8+ KB

In [36]:
df_raw['customers_raw']['customer.shipping_addresses'][19] # de aca podemos obtener ubicacion (city, country,municipality )

'[{"name": "ACEMARCHILELTDA", "surname": "-", "address": "Raul Toro 144", "city": "Valpara\\u00edso", "postal": "0000000", "country": "CL", "region": "01", "taxid": "76375827-3", "primary": true, "municipality_code": "8261239", "municipality": "Vi\\u00f1a del Mar"}]'

In [45]:
# customer_additional_fields  
df_raw['customers_raw']['customer.customer_additional_fields'][20] # de aca podemos obtener ubicacion (city, country,municipality )

'[{"id": 29542374, "label": "accepts_marketing", "value": "No", "area": "contact", "customer_id": 17188979, "checkout_custom_field_id": null}, {"id": 29542375, "label": "additional_information", "value": null, "area": "shipping", "customer_id": 17188979, "checkout_custom_field_id": null}, {"id": 29542376, "label": "additional_information", "value": null, "area": "billing", "customer_id": 17188979, "checkout_custom_field_id": null}, {"id": 29542377, "label": "Acepto emails de promociones", "value": null, "area": "other", "customer_id": 17188979, "checkout_custom_field_id": 53226}, {"id": 29542378, "label": "<p>\\u00bfBoleta o Factura? <br></p>", "value": "Boleta", "area": "other", "customer_id": 17188979, "checkout_custom_field_id": 55302}, {"id": 29542379, "label": "<p>Nombre empresa: (llenar solo para factura)</p>", "value": null, "area": "other", "customer_id": 17188979, "checkout_custom_field_id": 54331}, {"id": 29542380, "label": "<p>Rut de empresa:<b> </b>(llenar solo para factura)</p>", "value": null, "area": "other", "customer_id": 17188979, "checkout_custom_field_id": 55306}, {"id": 29542381, "label": "<p>Giro empresa: (llenar solo para factura)</p>", "value": null, "area": "other", "customer_id": 17188979, "checkout_custom_field_id": 55307}, {"id": 29542382, "label": "<p>Direcci\\u00f3n para factura: (llenar solo para factura)</p>", "value": null, "area": "other", "customer_id": 17188979, "checkout_custom_field_id": 55305}]'

In [25]:
len(df_raw['customers_raw'][df_raw['customers_raw']['customer.shipping_addresses']=='[]' ])

1034

In [46]:
len(df_raw['customers_raw'][df_raw['customers_raw']['customer.billing_addresses']!='[]' ])

593

In [41]:
# cantidad de categorias con contenido
len(df_raw['customers_raw'][df_raw['customers_raw']['customer.customer_categories']=='[]'])

1634

In [44]:
len(df_raw['customers_raw'][df_raw['customers_raw']['customer.customer_additional_fields']!='[]'])

516

visualizar la cantidad

In [49]:
columnas_lista=['shipping_addresses', 'billing_addresses', 'customer_categories','customer_additional_fields']
for col in columnas_lista:
    nro_filas=len(df_raw['customers_raw'][df_raw['customers_raw'][f'customer.{col}']!='[]'])
    print(f'Filas con contenido, para {col}: {nro_filas}')
    # print()

Filas con contenido, para shipping_addresses: 618
Filas con contenido, para billing_addresses: 593
Filas con contenido, para customer_categories: 18
Filas con contenido, para customer_additional_fields: 516

**Recuerda** que los datos aumentan, entonces los nulos van a variar, aplica transformaciones generales apra cada columna, solo las más importantes

In [27]:
df_raw['customers_raw'].isnull().sum()

customer.id                               0
customer.email                            0
customer.phone                          138
customer.phone_prefix                   218
customer.status                           0
customer.accepts_marketing                1
customer.accepted_marketing_at          507
customer.cancelled_marketing_at        1652
customer.fullname                         0
customer.unconfirmed_email             1652
customer.shipping_addresses               0
customer.billing_addresses                0
customer.customer_categories              0
customer.customer_additional_fields       0
dtype: int64

In [28]:
df_raw['customers_raw'].columns.to_list()

['customer.id',
 'customer.email',
 'customer.phone',
 'customer.phone_prefix',
 'customer.status',
 'customer.accepts_marketing',
 'customer.accepted_marketing_at',
 'customer.cancelled_marketing_at',
 'customer.fullname',
 'customer.unconfirmed_email',
 'customer.shipping_addresses',
 'customer.billing_addresses',
 'customer.customer_categories',
 'customer.customer_additional_fields']

In [ ]:
# se eliminan columnas con muchos nulos o irrelevantes para analisis posterior
columnas= df_raw['customers_raw'].columns.to_list()
# columnas a filtrar
columnas_filtro= ['customer.id', 
'customer.fullname',
 'customer.status',
 'customer.accepts_marketing',
 'customer.shipping_addresses']

customer_df= df_raw['customers_raw'][columnas_filtro]
# normalizacion columnas
customer_df.columns = [col.replace('customer.', 'cliente_') for col in customer_df.columns]

In [142]:
customer_df.head(5)

,cliente_id,cliente_fullname,cliente_status,cliente_accepts_marketing,cliente_shipping_addresses
0,17276830,Francisca Fuenzalida,approved,False,"[{""name"": ""Francisca"", ""surname"": ""Fuenzalida""..."
1,15462049,Oscar Herrera,approved,False,"[{""name"": ""2TCLOUD"", ""surname"": ""-"", ""address""..."
2,17506887,Julio Fuenzalida Cortes,approved,False,"[{""name"": ""Julio"", ""surname"": ""Fuenzalida cort..."
3,16776276,a.avalos33@hotmail.com,approved,True,[]
4,16979494,Alexis Burgos Arcos,approved,False,"[{""name"": ""Alexis"", ""surname"": ""Burgos Arcos"",..."

In [68]:
customer_df.isnull().sum()

customer.id                    0
customer.status                0
customer.accepts_marketing     1
customer.shipping_addresses    0
dtype: int64

In [144]:
import json

def parse_direcciones(fila):
    try:
        fila_parseada=json.loads(fila)
        if not fila_parseada: # si esta vacio
            return pd.Series([None, None, 'CL'])
        
        dicc = fila_parseada[0] # el primer elemento que es un diccionario
        ouput= pd.Series([dicc.get('city'), dicc.get('municipality'), dicc.get('country')])
        
        return ouput
    except Exception:
        return pd.Series([None, None, 'CL'])

# aplica sobre el df
columnas_nuevas= ['cliente_ciudad', 'cliente_municipalidad', 'cliente_pais'] 
customer_df[columnas_nuevas]= customer_df['cliente_shipping_addresses'].apply(parse_direcciones)

# eliminamos columna
customer_df.drop('cliente_shipping_addresses',  axis=1, inplace=True)

C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\4104912741.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customer_df[columnas_nuevas]= customer_df['cliente_shipping_addresses'].apply(parse_direcciones)
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\4104912741.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customer_df[columnas_nuevas]= customer_df['cliente_shipping_addresses'].apply(parse_direcciones)
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\4104912741.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customer_df[columnas_nuevas]= customer_df['cliente_shipping_addresses'].apply(parse_direcciones)
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\4104912741.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customer_df.drop('cliente_shipping_addresses',  axis=1, inplace=True)

Customer_resultante

In [145]:
customer_df

,cliente_id,cliente_fullname,cliente_status,cliente_accepts_marketing,cliente_ciudad,cliente_municipalidad,cliente_pais
0,17276830,Francisca Fuenzalida,approved,False,La Serena,La Serena,CL
1,15462049,Oscar Herrera,approved,False,Marga Marga,Quilpué,CL
2,17506887,Julio Fuenzalida Cortes,approved,False,Santiago,Ñuñoa,CL
3,16776276,a.avalos33@hotmail.com,approved,True,None,None,CL
4,16979494,Alexis Burgos Arcos,approved,False,Osorno,Osorno,CL
...,...,...,...,...,...,...,...
1647,17608176,sara.albornoz.b@usach.cl,approved,False,None,None,CL
1648,17583147,David Morales Romo,approved,False,Valparaiso,Valparaíso,CL
1649,17600474,Sebastián Mora,approved,False,SANTIAGO,Ñuñoa,CL
1650,17620302,Ismael Cáceres Cáceres,approved,False,Calama,Calama,CL
1651,17599569,Sebastian Widner,approved,False,La serena,La Serena,CL

NULOS

In [149]:
customer_df.isnull().sum()

cliente_id                      0
cliente_fullname                0
cliente_status                  0
cliente_accepts_marketing       1
cliente_ciudad               1034
cliente_municipalidad        1034
cliente_pais                    0
dtype: int64

In [154]:
customer_df['cliente_accepts_marketing'].unique()

array([False, True, None], dtype=object)

In [156]:
customer_df.columns.to_list()

['cliente_id',
 'cliente_fullname',
 'cliente_status',
 'cliente_accepts_marketing',
 'cliente_ciudad',
 'cliente_municipalidad',
 'cliente_pais']

In [158]:
# Flags de missing para variables clave
df= customer_df
for col in ['cliente_ciudad', 'cliente_municipalidad', 'cliente_accepts_marketing']:
    df[f'{col}_missing'] = df[col].isna().astype(int)

# acepta marketing: crear versión tri-state y booleana
df['cliente__marketing_cat'] = df['cliente_accepts_marketing'].fillna('Sin especificar') # para analisis categorico

columnas= ['cliente_fullname','cliente_status','cliente_ciudad','cliente_municipalidad','cliente_pais']
df[columnas] = df[columnas].fillna('Sin especificar')

C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\2221070206.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'{col}_missing'] = df[col].isna().astype(int)
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\2221070206.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'{col}_missing'] = df[col].isna().astype(int)
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\2221070206.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'{col}_missing'] = df[col].isna().astype(int)
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\2221070206.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cliente__marketing_cat'] = df['cliente_accepts_marketing'].fillna('Sin especificar') # para analisis categorico
C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\2221070206.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[columnas] = df[columnas].fillna('Sin especificar')

In [ ]:
type(customer_df['cliente_accepts_marketing'][0])

bool

In [148]:
duplicados= customer_df.duplicated().sum()
id_unicos= customer_df['cliente_id'].nunique() == len(customer_df)
print(duplicados, id_unicos)

0 True

In [171]:
prueba_customer=transform_customers(df_raw['customers_raw'])
prueba_customer.head(4)

C:\Users\Angelica\AppData\Local\Temp\ipykernel_27484\3832340403.py:62: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['cliente_accepts_marketing'] = df['cliente_accepts_marketing'].fillna(False)

,cliente_id,cliente_fullname,cliente_status,cliente_accepts_marketing,cliente_ciudad,cliente_municipalidad,cliente_pais,cliente_ciudad_missing,cliente_municipalidad_missing,cliente_accepts_marketing_missing,cliente_marketing_cat
0,17276830,Francisca Fuenzalida,approved,False,La Serena,La Serena,CL,0,0,0,No
1,15462049,Oscar Herrera,approved,False,Marga Marga,Quilpué,CL,0,0,0,No
2,17506887,Julio Fuenzalida Cortes,approved,False,Santiago,Ñuñoa,CL,0,0,0,No
3,16776276,a.avalos33@hotmail.com,approved,True,Sin especificar,Sin especificar,CL,1,1,0,Si

In [169]:
prueba_customer

,cliente_id,cliente_status,cliente_accepts_marketing,cliente_ciudad,cliente_municipalidad,cliente_pais,cliente_ciudad_missing,cliente_municipalidad_missing,cliente_accepts_marketing_missing,cliente_marketing_cat
0,17276830,approved,False,La Serena,La Serena,CL,0,0,0,No
1,15462049,approved,False,Marga Marga,Quilpué,CL,0,0,0,No
2,17506887,approved,False,Santiago,Ñuñoa,CL,0,0,0,No
3,16776276,approved,True,Sin especificar,Sin especificar,CL,1,1,0,Si
4,16979494,approved,False,Osorno,Osorno,CL,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...
1647,17608176,approved,False,Sin especificar,Sin especificar,CL,1,1,0,No
1648,17583147,approved,False,Valparaiso,Valparaíso,CL,0,0,0,No
1649,17600474,approved,False,SANTIAGO,Ñuñoa,CL,0,0,0,No
1650,17620302,approved,False,Calama,Calama,CL,0,0,0,No
1651,17599569,approved,False,La serena,La Serena,CL,0,0,0,No

Siguiente: 
- Finalizar pasos (funcion) para la parte de Transform de *'customers_raw'*
- Ojo: no demores mucho en analizar, solo dejarlo limpio y normalizado

##

#### **Función TRANSFORM para products_raw**

In [178]:
print(len(df_raw['products_raw']))
df_raw['products_raw'].head(2)

1230

,product.id,product.name,product.page_title,product.description,product.meta_description,product.price,product.cost_per_item,product.compare_at_price,product.weight,product.stock,...,product.width,product.height,product.diameter,product.google_product_category,product.images,product.variants,product.fields,product.permalink,product.discount,product.currency
0,27766653,Cámara Canon Mirrorless EOS R8 Body,Cámara Canon Mirrorless EOS R8 Body,"<div class=""product-description""><h1>\n ...",Canon EOS R8: Desempeño excepcional y...,1999990,NaN,2499990.0,1.4,1,...,10.0,20.0,0,141,"[{""id"": 57589702, ""url"": ""https://images.jumps...",[],"[{""id"": 13528130, ""custom_field_id"": 68122, ""t...",5803c002aa,0.0,CLP
1,27766654,Cámara Canon Mirrorless EOS R6 MKII Body,Cámara Canon Mirrorless EOS R6 MKII Body,"<div class=""product-description""><h1>Canon EOS...",Canon EOS R6 Mark II: Desempeño multimedia exc...,2989990,NaN,NaN,1.5,1,...,10.0,20.0,0,141,"[{""id"": 57590020, ""url"": ""https://images.jumps...",[],"[{""id"": 13528139, ""custom_field_id"": 68122, ""t...",5666c003aa,0.0,CLP

In [194]:
df['product.currency'].value_counts()

product.currency
CLP    1230
Name: count, dtype: int64

In [ ]:
# Ahora vamos con products_raw
def transform_products(df):
    columnas_filtro= ['product.id',
    'product.name',
    'product.price',
    'product.stock',
    'product.stock_unlimited',
    'product.stock_threshold',
    'product.stock_notification',
    'product.brand',
    'product.reviews_enabled',
    'product.status',
    'product.created_at',
    'product.updated_at',
    'product.currency']

    # --- 1. Filtro de columnas
    df = df[columnas_filtro].copy()

    # --- 2. Renombrado
    df.columns = [col.replace('product.', 'producto_') for col in df.columns]

    # --- 3. Relleno de categóricas
    cols_categoricas = ['producto_name', 'producto_brand', 'producto_status', 'producto_currency']
    df[cols_categoricas] = df[cols_categoricas].fillna('Sin especificar')

    # --- 3. Manejo de fechas
    for col in ['producto_created_at', 'producto_updated_at']:
        df[col] = pd.to_datetime(df[col], errors='coerce').dt.date  # solo YYYY-MM-DD

    # --- 4. Manejo de precio
    df['producto_price']=df['producto_price'].fillna(0)

    # Resultado final
    df_clean = df.copy()
    return df_clean

df= df_raw['products_raw']
products_clean= transform_products(df)

In [14]:
type(products_clean['producto_price'][0])

numpy.int64

In [15]:
products_clean.head(5)

,producto_id,producto_name,producto_price,producto_stock,producto_stock_unlimited,producto_stock_threshold,producto_stock_notification,producto_brand,producto_reviews_enabled,producto_status,producto_created_at,producto_updated_at,producto_currency
0,27766653,Cámara Canon Mirrorless EOS R8 Body,1999990,1,False,0,True,Canon,True,available,2024-11-23,2025-08-12,CLP
1,27766654,Cámara Canon Mirrorless EOS R6 MKII Body,2989990,1,False,0,True,Canon,True,available,2024-11-23,2025-08-05,CLP
2,27766655,Cámara Canon Mirrorless EOS R50 Body,1999990,0,False,0,True,Canon,True,available,2024-11-23,2025-01-16,CLP
3,27766656,Cámara Canon Mirrorless EOS R7 - Body,1549990,0,False,0,True,Canon,True,available,2024-11-23,2025-04-14,CLP
4,27766667,Cámara Sony A7 III Body,1399990,2,False,0,True,Sony,True,available,2024-11-23,2025-08-05,CLP

In [10]:
products_clean.isnull().sum()

producto_id                    0
producto_name                  0
producto_price                 0
producto_stock                 0
producto_stock_unlimited       0
producto_stock_threshold       0
producto_stock_notification    0
producto_brand                 0
producto_reviews_enabled       0
producto_status                0
producto_created_at            0
producto_updated_at            0
producto_currency              0
dtype: int64

#### **Función TRANSFORM para orders_raw**

In [43]:
len(customer_clean)

1652

In [78]:
len(df_raw['orders_raw'])

1781

In [42]:
df_raw['orders_raw'].head(5)

,order.id,order.source.created_from,order.source.created_from_app_code,order.source.source_name,order.source.medium,order.source.campaign,order.source.referral_url,order.source.referral_code,order.source.user_agent,order.source.first_page_visited,...,order.billing_address.region,order.billing_address.country,order.billing_address.country_code,order.billing_address.region_code,order.billing_address.street_number,order.billing_address.complement,order.billing_address.municipality,order.shipping_address,order.shipping_branch,order.customer
0,2679,checkout,None,js-google-shopping-app,js-google-shopping-app,None,https://www.google.com/,None,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://www.kreadores.pro/microfono-inalambric...,...,None,None,None,None,None,None,None,None,None,None
1,2678,checkout,None,revie,revie_star,revie,None,None,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,https://www.kreadores.pro/ilce-6400l/b,...,Región Metropolitana,Chile,CL,12,None,casa,Vitacura,None,None,None
2,2677,checkout,None,js-google-shopping-app,js-google-shopping-app,None,https://www.google.com/,None,Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like...,https://www.kreadores.pro/microfono-dinamico-m...,...,None,None,None,None,None,None,None,None,None,None
3,2676,checkout,None,js-google-shopping-app,js-google-shopping-app,None,https://www.google.com/,None,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://www.kreadores.pro/tripode-joby-compact...,...,None,None,None,None,None,None,None,None,None,None
4,2675,checkout,None,js-google-shopping-app,js-google-shopping-app,None,None,None,Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...,https://www.kreadores.pro/adaptador-canon-ef-e...,...,None,None,None,None,None,None,None,None,None,None

In [54]:
# visualizar todas las columnas
pd.set_option('display.max_columns', None)  # mostrar todas las columnas

In [154]:
customer_clean[customer_clean['cliente_id']==17569269]

,cliente_id,cliente_fullname,cliente_status,cliente_accepts_marketing,cliente_ciudad,cliente_municipalidad,cliente_pais,cliente_ciudad_missing,cliente_municipalidad_missing,cliente_accepts_marketing_missing,cliente_marketing_cat
327,17569269,Clemente De,approved,False,Santiago,Vitacura,Chile,0,0,0,No

In [87]:
products_clean[products_clean['producto_id']==28363657]

,producto_id,producto_name,producto_price,producto_stock,producto_stock_unlimited,producto_stock_threshold,producto_stock_notification,producto_brand,producto_reviews_enabled,producto_status,producto_created_at,producto_updated_at,producto_currency
551,28363657,Micrófono inalámbrico lavalier DJI Mic Mini doble,167990,45,False,0,False,DJI,True,available,2025-01-23,2025-08-27,CLP

In [289]:
orders_clean= transform_orders(df_raw['orders_raw'])
orders_clean.head(2)

,id_orden,fecha_creacion,fecha_completacion,moneda,precio_total,estado_cumplimiento,empresa_envio,id_cliente,region_envio,pais_envio,municipalidad_envio,estado_orden,estado_envio,estado_cliente,productos_ids
0,2679,2025-08-27,NaT,CLP,167990,No cumplido,Envío Express,0,O'Higgins,Chile,Marchihue,Abandonada,No procesado,No Registrado,28363657
1,2678,2025-08-27,2025-08-27,CLP,839990,No cumplido,Envío Express,17569269,Región Metropolitana,Chile,Vitacura,Pagada,No procesado,Registrado,27766673

In [290]:
orders_products = create_orders_products(orders_clean)
orders_products.head(5)

   id_orden  id_producto
0      2679     28363657
1      2678     27766673
2      2677     27831873
3      2676     29248187
4      2675     27795774

In [282]:
print(len(orders_products))
orders_products['id_orden'].nunique()

2233

1781

In [273]:
orders_clean['empresa_envio'].unique()

array(['Envío Express', 'Sin especificar', 'Prioritario a domicilio',
       'Blue Express', 'Estándar a domicilio', 'Prioritario a sucursal',
       'Estándar a sucursal', 'Prioritario', 'BluExpress Priority',
       'Correo Ordinario', 'BluExpress Express'], dtype=object)

In [269]:
orders_clean['empresa_envio_normalizada'].unique()

array(['Envío Express', 'Sin especificar', 'Prioritario a domicilio',
       'Blue Express', 'Estándar a domicilio', 'Prioritario a sucursal',
       'Estándar a sucursal', 'Prioritario', 'BluExpress Priority',
       'Correo Ordinario', 'BluExpress Express'], dtype=object)

columnas relevantes
- id, name, price, stock, stock_notification, brand, created_at, update_at, categories

### FLUJO DE EJECUCIÓN

In [ ]:
endpoints

['products', 'customers', 'orders']

#### 1. Ejecución de extracción(data_raw)

In [ ]:
# endpoints
# customers_raw=extract_supabase_raw(endpoint='customers')
# products_raw= extract_supabase_raw('products')
# orders_raw= extract_supabase_raw('orders')
from tqdm import tqdm

df_raw= {}
for endpoint in tqdm(endpoints):
    df_raw[f'{endpoint}_raw']= extract_supabase_raw(endpoint=endpoint)